import type { Metadata } from 'next';
import { Rosario } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';

const rosario = Rosario({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rosario.className}>
        <div className="container">
          <div className="wrapper">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
